Add httpclient exclusions back to pom.xml to prevent runtime exception "java.lang.NoClassDefFoundError: Lorg/apache/commons/httpclient/HttpClient" (cherry picked from commit 8d3df56e38f710b8b1f4610040a0f3f80cc5a246)